apiVersion: v1
kind: Service
metadata:
  name: portfolio
spec:
  type: NodePort
  selector:
    app: portfolio
  ports:
    - port: 5173
      protocol: TCP
      targetPort: 5173
      nodePort: 31000
